version: '3'

services:
    backend:
        build:
            context: .
            dockerfile: ./backend.Dockerfile
        volumes:
            - ./django_rest/:/django_rest/
        ports:
            - 8000:8000
        command:
            bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    frontend:
        build:
            context: .
            dockerfile: ./frontend.Dockerfile
        volumes:
            - ./frontend:/frontend
        ports:
            - 4200:4200
        command:
            bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"